apiVersion: apps/v1
kind: Deployment
metadata:
  name: api_name-deployment
  namespace: cloudnxt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api_name-api
  template:
    metadata:
      labels:
        app: api_name-api
    spec:
      containers:
      - name: api_name-api
        image: rohitrustagi007/api_name:latest
        imagePullPolicy: Always
        env: 
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
          - name: AWS_ACCESS_KEY
            valueFrom: 
              secretKeyRef:
                name: access 
                key: AWS_ACCESS_KEY
          - name: AWS_SECRET_KEY
            valueFrom: 
              secretKeyRef:
                name: secret 
                key: AWS_SECRET_KEY       
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

